services:
  loki:
    image: grafana/loki:2.9.15
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      j-grafana-network:
        ipv4_address: 172.20.0.3
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - "${LOKI_STORAGE_DIR}/index:/loki/index"
      - "${LOKI_STORAGE_DIR}/chunks:/loki/chunks"
      - "${LOKI_STORAGE_DIR}/cache:/loki/boltdb-cache"
      - "${LOKI_STORAGE_DIR}/compactor:/loki/compactor"

  promtail:
    image: grafana/promtail:2.9.15
    container_name: promtail
    networks:
      j-grafana-network:
        ipv4_address: 172.20.0.4
    ports:
      - "9080:9080"
    volumes:
      - ./promtail-data:/promtail
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    depends_on:
      - loki

  grafana:
    image: grafana/grafana-oss:10.2.2
    container_name: grafana
    networks:
      j-grafana-network:
        ipv4_address: 172.20.0.2
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3000}
      - GF_SECURITY_ADMIN_USER=rdn
      - GF_SECURITY_ADMIN_PASSWORD=rdn
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:

networks:
  j-grafana-network:
    name: j-grafana-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
