server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /promtail/positions.yaml

scrape_configs:
  - job_name: docker-logs
    # read Docker socket
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 10s
        filters:
          - name: name
            values: ["api", "rabbitmq", "payments", "worker"]
    #  drop-rules
    relabel_configs:
      # alternative filter-rules
      - source_labels: [__meta_docker_container_name]
        regex: "/(api|rabbitmq|payments|worker)$"
        action: keep
      # drop system containers
      - source_labels: [__meta_docker_container_name]
        regex: "/(grafana|loki|promtail)$"
        action: drop
      # select a path ID containers
      - source_labels: ["__meta_docker_container_id"]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*.log*
      # set name of container
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: container_name
