FROM node:22-alpine AS dev

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/

RUN npm install --workspace=apps/api

COPY packages ./packages
COPY . .

EXPOSE 3015

CMD ["npm", "run", "dev:api"]
