name: build-and-stage

on:
  push:
    branches: [develop]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install deps
        run: npm ci

      - name: Set image tag
        id: vars
        run: echo "TAG=sha-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Debug working directory
        shell: powershell
        run: |
          Write-Host "GITHUB_WORKSPACE=$env:GITHUB_WORKSPACE"
          Write-Host "PWD=$(Get-Location)"
          Get-ChildItem $env:GITHUB_WORKSPACE

      - name: Build API image
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: docker build -f apps/api/Dockerfile.prod --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" -t ghcr.io/${{ github.repository_owner }}/journeyproject-api:${{ steps.vars.outputs.TAG }} .

      - name: Build Payments image
        shell: powershell
        working-directory: ${{ github.workspace }}
        run: docker build -f apps/payments/Dockerfile.prod --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" -t ghcr.io/${{ github.repository_owner }}/journeyproject-payments:${{ steps.vars.outputs.TAG }} .

      - name: Get API image digest
        id: digest
        run: |
          docker inspect ghcr.io/${{ github.repository }}/api:${{ steps.vars.outputs.TAG }} --format='{{index .RepoDigests 0}}' > digest.txt

      - name: Create release manifest
        run: |
          echo '{
            "commit": "${{ github.sha }}",
            "services": {
              "api": {
                "image": "ghcr.io/${{ github.repository }}/api:${{ steps.vars.outputs.TAG }}"
              },
              "worker": {
                "image": "ghcr.io/${{ github.repository }}/api:${{ steps.vars.outputs.TAG }}"
              },
              "payments": {
                "image": "ghcr.io/${{ github.repository }}/payments:${{ steps.vars.outputs.TAG }}"
              }
            }
          }' > release-manifest.json

      - name: Upload manifest
        uses: actions/upload-artifact@v4
        with:
          name: release-manifest
          path: release-manifest.json
